In [2]:
import numpy as np

In [44]:
def boundaries(seq, domain):
	"""
		Defines a boundary as the beginning of a domain or the end of the last domain
	"""
	last_end = 0
	bounds = np.zeros((len(seq)), dtype=np.int8)
	for k, v in domain.items():
		boundary_positions = v.split(',')
		for b in boundary_positions:
			start, end = [int(i) for i in b.split('-')]
			if end > last_end:
				last_end = end
			bounds[start-1] = 1
	bounds[last_end-1] = 1            
	return np.array(bounds, dtype=np.bool_)


def boundaries2(seq, domain):
	"""
		Defines a boundary as the beginning of a domain ONLY in multi-domain proteins
	"""
	first_start = np.inf
	bounds = np.zeros((len(seq)), dtype=np.int8)
	for k, v in domain.items():
		boundary_positions = v.split(',')
		for b in boundary_positions:
			start, end = [int(i) for i in b.split('-')]
			if start < first_start:
				first_start = start
			bounds[start-1] = 1
	bounds[first_start-1] = 0            
	return np.array(bounds, dtype=np.bool_)

In [41]:
d = {'1' : '1-5', '2' : '6-10'}
s = "".join(['A'] * 10)

In [53]:
a = boundaries(s, d).astype(np.float)
a

/tmp/ipykernel_83484/1936535553.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = boundaries(s, d).astype(np.float)


array([1., 0., 0., 0., 0., 1., 0., 0., 0., 1.])

In [54]:
b = boundaries2(s, d).astype(np.float)
b

/tmp/ipykernel_83484/2161093989.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = boundaries2(s, d).astype(np.float)


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [55]:
print(a)
for i in range(len(a)):
	if a[i] == True:
		a[i] = False
		break

for i in range(len(a)-1, -1, -1):
	if a[i] == True:
		a[i] = False
		break

print(a)

(a == b).all()


[1. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


True